# Generated by Django 5.0.7 on 2024-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('isDone', models.BooleanField(default=False)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
