# Generated by Django 5.0.7 on 2024-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
