# Generated by Django 5.0.7 on 2024-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0004_alter_userstodolist_sessionkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
        migrations.AlterField(
            model_name='userstodolist',
            name='sessionKey',
            field=models.TextField(),
        ),
    ]
