# Generated by Django 5.0.7 on 2024-08-27 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_messagereadbyuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereadbyuser',
            name='readAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContactMessageReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isClient', models.BooleanField()),
                ('replyMessage', models.TextField()),
                ('replyDate', models.DateTimeField(auto_now_add=True)),
                ('contactMessageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactUs.contactmessage')),
                ('replyUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
