# Generated by Django 5.0.7 on 2024-08-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0004_alter_contactmessagereplies_replyuserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('expiryDate', models.DateTimeField()),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactUs.contactmessage')),
            ],
        ),
    ]
