# Generated by Django 5.0.7 on 2024-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxTypeName', models.IntegerField()),
                ('trxTypeText', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
