# Generated by Django 5.0.7 on 2024-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isDevNote',
            field=models.BooleanField(),
        ),
    ]
